begin;

create table if not exists public.team_weekly_challenges (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  week_start date not null,
  game_ids text[] not null default array['queens','tango','zip','minisudoku','geo']::text[],
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique(team_id, week_start)
);

alter table public.team_weekly_challenges enable row level security;

drop policy if exists "team members can view weekly challenges" on public.team_weekly_challenges;
create policy "team members can view weekly challenges"
on public.team_weekly_challenges for select to authenticated
using (exists(select 1 from public.team_members tm where tm.team_id=team_weekly_challenges.team_id and tm.user_id=auth.uid()));

alter table public.game_stats
  add column if not exists team_challenge_id bigint references public.team_weekly_challenges(id) on delete set null,
  add column if not exists team_id bigint references public.teams(id) on delete set null;

drop index if exists public.game_stats_one_challenge_per_day;
create unique index if not exists game_stats_one_challenge_per_scope
on public.game_stats(user_id,game,challenge_date,coalesce(team_challenge_id,0))
where mode='challenge';

create or replace function public.current_week_start()
returns date language sql stable as $$
  select (current_date - ((extract(isodow from current_date)::int)-1))::date
$$;

create or replace function public.get_my_active_team_challenges()
returns table(challenge_id bigint,team_id bigint,team_name text,team_emoji text,game_ids text[])
language sql security definer stable set search_path=public as $$
  select twc.id,t.id,t.name,coalesce(t.emoji,'⭐'),twc.game_ids
  from public.team_members tm
  join public.teams t on t.id=tm.team_id
  join public.team_weekly_challenges twc on twc.team_id=t.id and twc.week_start=public.current_week_start()
  where tm.user_id=auth.uid()
  order by t.name
$$;

grant execute on function public.get_my_active_team_challenges() to authenticated;

create or replace function public.set_team_weekly_challenge(target_team_id bigint,selected_games text[])
returns bigint language plpgsql security definer set search_path=public as $$
declare result_id bigint;
begin
  if not exists(select 1 from public.teams t where t.id=target_team_id and t.created_by=auth.uid()) then
    raise exception 'Only the team owner can set its challenge.' using errcode='42501';
  end if;
  if coalesce(array_length(selected_games,1),0)=0 then raise exception 'Choose at least one game.'; end if;
  insert into public.team_weekly_challenges(team_id,week_start,game_ids,created_by)
  values(target_team_id,public.current_week_start(),selected_games,auth.uid())
  on conflict(team_id,week_start) do update set game_ids=excluded.game_ids,updated_at=now()
  returning id into result_id;
  return result_id;
end;
$$;
grant execute on function public.set_team_weekly_challenge(bigint,text[]) to authenticated;

create or replace function public.notify_team_daily_challenge_completed()
returns trigger language plpgsql security definer set search_path=public as $$
declare player_name text; game_label text; notification_body text;
begin
  if new.mode is distinct from 'challenge' or new.challenge_date is null or new.team_challenge_id is null or new.team_id is null then return new; end if;
  select coalesce(nullif(btrim(p.name),''),'A teammate') into player_name from public.profiles p where p.id=new.user_id;
  game_label:=case lower(new.game) when 'queens' then 'Queens' when 'tango' then 'Tango' when 'zip' then 'Zip' when 'minisudoku' then 'Mini Sudoku' when 'geo' then 'Geo' else initcap(replace(new.game,'_',' ')) end;
  notification_body:=format('🏁 %s finished the %s team challenge! Think you can beat them? 🎮',coalesce(player_name,'A teammate'),game_label);
  insert into public.direct_messages(sender_id,recipient_id,body,system_generated,activity_type,source_stat_id)
  select new.user_id,tm.user_id,notification_body,true,'team_daily_challenge',new.id
  from public.team_members tm where tm.team_id=new.team_id and tm.user_id<>new.user_id
  on conflict do nothing;
  return new;
end;$$;

notify pgrst,'reload schema';
commit;
