-- v205: Share an exact completed puzzle with every eligible player in the
-- challenger's circles. One source result can only be shared once, and a
-- player appearing in several shared circles receives one challenge.

begin;

create table if not exists public.score_challenges (
  id bigint generated by default as identity primary key,
  source_stat_id bigint not null unique references public.game_stats(id) on delete cascade,
  challenger_id uuid not null references public.profiles(id) on delete cascade,
  game text not null check (game in ('hive','tango','gridly','minisudoku')),
  seed text not null,
  generator_version text,
  generator_config jsonb,
  day_index integer not null,
  seconds integer not null check (seconds>=0),
  created_at timestamptz not null default now()
);

create table if not exists public.score_challenge_recipients (
  challenge_id bigint not null references public.score_challenges(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  completed_stat_id bigint references public.game_stats(id) on delete set null,
  completed_at timestamptz,
  primary key(challenge_id,recipient_id)
);

create index if not exists score_challenge_recipients_player_idx
  on public.score_challenge_recipients(recipient_id,completed_at,challenge_id);

alter table public.score_challenges enable row level security;
alter table public.score_challenge_recipients enable row level security;

-- The tables are deliberately RPC-only. This avoids exposing another
-- player's seed or circle recipient list through PostgREST; each definer RPC
-- below performs its own participant/ownership check.
revoke all on public.score_challenges from anon,authenticated;
revoke all on public.score_challenge_recipients from anon,authenticated;

create or replace function public.create_score_challenge(target_stat_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  source_result public.game_stats;
  created_challenge_id bigint;
  recipient_count integer;
  challenger_name text;
  game_label text;
  already_sent boolean:=false;
begin
  select * into source_result
  from public.game_stats result
  where result.id=target_stat_id;

  if not found or source_result.user_id is distinct from auth.uid() then
    raise exception 'Game result not found.' using errcode='42501';
  end if;
  if source_result.game not in ('hive','tango','gridly','minisudoku') then
    raise exception 'Score challenges are not available for this game.' using errcode='22023';
  end if;
  if nullif(source_result.seed,'') is null then
    raise exception 'This result cannot reproduce the original puzzle.' using errcode='22023';
  end if;
  if exists(
    select 1 from public.profiles profile
    where profile.id=auth.uid()
      and (
        profile.account_deleted_at is not null
        or coalesce(profile.is_blocked,false)
        or coalesce(profile.hidden_from_others,false)
        or coalesce(profile.is_approved,true)=false
      )
  ) then
    raise exception 'This account cannot send score challenges.' using errcode='42501';
  end if;

  insert into public.score_challenges(
    source_stat_id,challenger_id,game,seed,generator_version,
    generator_config,day_index,seconds
  ) values (
    source_result.id,source_result.user_id,source_result.game,source_result.seed,
    source_result.generator_version,source_result.generator_config,
    source_result.day_index,source_result.seconds
  ) on conflict(source_stat_id) do nothing
  returning id into created_challenge_id;

  if created_challenge_id is null then
    already_sent:=true;
    select challenge.id into created_challenge_id
    from public.score_challenges challenge
    where challenge.source_stat_id=source_result.id;
  else

    insert into public.score_challenge_recipients(challenge_id,recipient_id)
    select distinct created_challenge_id,other_member.user_id
    from public.circle_members my_membership
    join public.circle_members other_member
      on other_member.circle_id=my_membership.circle_id
    join public.profiles recipient_profile
      on recipient_profile.id=other_member.user_id
    where my_membership.user_id=auth.uid()
      and other_member.user_id<>auth.uid()
      and recipient_profile.account_deleted_at is null
      and coalesce(recipient_profile.is_blocked,false)=false
      and coalesce(recipient_profile.hidden_from_others,false)=false
      and coalesce(recipient_profile.is_approved,true)=true
      and not exists(
        select 1 from public.circle_member_blocks blocked
        where blocked.circle_id=my_membership.circle_id
          and blocked.user_id=other_member.user_id
      )
    on conflict do nothing;

    select count(*)::integer into recipient_count
    from public.score_challenge_recipients recipient
    where recipient.challenge_id=created_challenge_id;

    if recipient_count=0 then
      delete from public.score_challenges where id=created_challenge_id;
      return jsonb_build_object(
        'challenge_id',null,
        'recipient_count',0,
        'already_sent',false
      );
    end if;

    select coalesce(profile.name,'A friend') into challenger_name
    from public.profiles profile where profile.id=auth.uid();
    game_label:=case source_result.game
      when 'hive' then 'Hive'
      when 'gridly' then 'Gridly'
      when 'minisudoku' then 'Sudoku'
      else 'Tango'
    end;

    insert into public.direct_messages(
      sender_id,recipient_id,body,system_generated,activity_type,source_stat_id
    )
    select
      recipient.recipient_id,recipient.recipient_id,
      format('%s finished %s in %s. Can you beat their score?',
        challenger_name,game_label,
        (source_result.seconds/60)::text||':'||lpad((source_result.seconds%60)::text,2,'0')),
      true,'score_challenge',source_result.id
    from public.score_challenge_recipients recipient
    where recipient.challenge_id=created_challenge_id
    on conflict do nothing;
  end if;

  select count(*)::integer into recipient_count
  from public.score_challenge_recipients recipient
  where recipient.challenge_id=created_challenge_id;

  return jsonb_build_object(
    'challenge_id',created_challenge_id,
    'recipient_count',recipient_count,
    'already_sent',already_sent
  );
end;
$$;

create or replace function public.get_score_challenge(target_source_stat_id bigint)
returns jsonb
language sql
security definer
set search_path=public
stable
as $$
  select jsonb_build_object(
    'id',challenge.id,
    'source_stat_id',challenge.source_stat_id,
    'challenger_id',challenge.challenger_id,
    'challenger_name',coalesce(profile.name,'A friend'),
    'game',challenge.game,
    'seed',challenge.seed,
    'generator_version',challenge.generator_version,
    'generator_config',challenge.generator_config,
    'day_index',challenge.day_index,
    'seconds',challenge.seconds,
    'completed_stat_id',recipient.completed_stat_id
  )
  from public.score_challenges challenge
  join public.profiles profile on profile.id=challenge.challenger_id
  join public.score_challenge_recipients recipient
    on recipient.challenge_id=challenge.id and recipient.recipient_id=auth.uid()
  where challenge.source_stat_id=target_source_stat_id;
$$;

create or replace function public.complete_score_challenge(
  target_challenge_id bigint,
  target_stat_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  challenge public.score_challenges;
  result public.game_stats;
  player_name text;
  outcome text;
begin
  select * into challenge from public.score_challenges where id=target_challenge_id;
  select * into result from public.game_stats where id=target_stat_id;

  if not found or result.user_id is distinct from auth.uid() then
    raise exception 'Game result not found.' using errcode='42501';
  end if;
  if not exists(
    select 1 from public.score_challenge_recipients recipient
    where recipient.challenge_id=challenge.id and recipient.recipient_id=auth.uid()
  ) then
    raise exception 'Score challenge not found.' using errcode='42501';
  end if;
  if result.game<>challenge.game or result.seed<>challenge.seed then
    raise exception 'The completed puzzle does not match this challenge.' using errcode='22023';
  end if;

  update public.score_challenge_recipients
  set completed_stat_id=result.id,completed_at=now()
  where challenge_id=challenge.id and recipient_id=auth.uid()
    and completed_stat_id is null;

  select coalesce(profile.name,'A friend') into player_name
  from public.profiles profile where profile.id=auth.uid();
  outcome:=case
    when result.seconds<challenge.seconds then
      format('%s beat your %s score: %s versus %s.',player_name,challenge.game,
        (result.seconds/60)::text||':'||lpad((result.seconds%60)::text,2,'0'),
        (challenge.seconds/60)::text||':'||lpad((challenge.seconds%60)::text,2,'0'))
    when result.seconds=challenge.seconds then
      format('%s tied your %s score at %s.',player_name,challenge.game,
        (result.seconds/60)::text||':'||lpad((result.seconds%60)::text,2,'0'))
    else
      format('%s tried your %s challenge: %s versus your %s.',player_name,challenge.game,
        (result.seconds/60)::text||':'||lpad((result.seconds%60)::text,2,'0'),
        (challenge.seconds/60)::text||':'||lpad((challenge.seconds%60)::text,2,'0'))
  end;

  insert into public.direct_messages(
    sender_id,recipient_id,body,system_generated,activity_type,source_stat_id
  ) values (
    challenge.challenger_id,challenge.challenger_id,outcome,true,'score_challenge_result',result.id
  ) on conflict do nothing;

  return jsonb_build_object(
    'beat_score',result.seconds<challenge.seconds,
    'tied_score',result.seconds=challenge.seconds,
    'their_seconds',challenge.seconds,
    'your_seconds',result.seconds
  );
end;
$$;

revoke all on function public.create_score_challenge(bigint) from public;
revoke all on function public.get_score_challenge(bigint) from public;
revoke all on function public.complete_score_challenge(bigint,bigint) from public;
grant execute on function public.create_score_challenge(bigint) to authenticated;
grant execute on function public.get_score_challenge(bigint) to authenticated;
grant execute on function public.complete_score_challenge(bigint,bigint) to authenticated;

notify pgrst,'reload schema';

commit;
