begin;

alter table public.team_weekly_challenges
  add column if not exists active_days integer[] not null default array[1,2,3,4,5,6,7]::integer[],
  add column if not exists reward_points integer not null default 100,
  add column if not exists locked_at timestamp with time zone;

alter table public.team_weekly_challenges
  drop constraint if exists team_weekly_challenges_reward_points_check;
alter table public.team_weekly_challenges
  add constraint team_weekly_challenges_reward_points_check check (reward_points between 0 and 100000);

create table if not exists public.team_challenge_reward_awards (
  id bigint generated by default as identity primary key,
  challenge_id bigint not null references public.team_weekly_challenges(id) on delete cascade,
  player_id uuid not null references public.profiles(id) on delete cascade,
  points integer not null check (points >= 0),
  awarded_at timestamp with time zone not null default now(),
  unique(challenge_id, player_id)
);

alter table public.team_challenge_reward_awards enable row level security;
drop policy if exists "players view own team challenge rewards" on public.team_challenge_reward_awards;
create policy "players view own team challenge rewards"
on public.team_challenge_reward_awards for select to authenticated
using (player_id=auth.uid() or public.is_admin(auth.uid()));

create or replace function public.get_my_active_team_challenges()
returns table(
  challenge_id bigint,
  team_id bigint,
  team_name text,
  team_emoji text,
  game_ids text[],
  active_days integer[],
  reward_points integer,
  active_today boolean,
  is_locked boolean
)
language sql security definer stable set search_path=public as $$
  select twc.id,t.id,t.name,coalesce(t.emoji,'⭐'),twc.game_ids,twc.active_days,twc.reward_points,
    extract(isodow from current_date)::integer = any(twc.active_days),
    (twc.locked_at is not null or exists(select 1 from public.game_stats gs where gs.team_challenge_id=twc.id))
  from public.team_members tm
  join public.teams t on t.id=tm.team_id
  join public.team_weekly_challenges twc on twc.team_id=t.id and twc.week_start=public.current_week_start()
  where tm.user_id=auth.uid()
  order by t.name
$$;
grant execute on function public.get_my_active_team_challenges() to authenticated;

drop function if exists public.set_team_weekly_challenge(bigint,text[]);
create or replace function public.set_team_weekly_challenge(
  target_team_id bigint,
  selected_games text[],
  selected_days integer[],
  reward_points_in integer
)
returns bigint language plpgsql security definer set search_path=public as $$
declare result_id bigint; clean_games text[]; clean_days integer[]; existing_id bigint;
begin
  if not exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_approved=true) then
    raise exception 'Your account must be approved first.' using errcode='42501';
  end if;
  if not exists(select 1 from public.teams t where t.id=target_team_id and t.created_by=auth.uid()) then
    raise exception 'Only this team creator can set its challenge.' using errcode='42501';
  end if;
  select array_agg(distinct g order by g) into clean_games from unnest(selected_games) g where g in ('queens','tango','zip','minisudoku','geo');
  select array_agg(distinct d order by d) into clean_days from unnest(selected_days) d where d between 1 and 7;
  if coalesce(array_length(clean_games,1),0)=0 then raise exception 'Choose at least one game.'; end if;
  if coalesce(array_length(clean_days,1),0)=0 then raise exception 'Choose at least one challenge day.'; end if;
  if coalesce(reward_points_in,0) < 0 or coalesce(reward_points_in,0) > 100000 then raise exception 'Reward must be between 0 and 100,000 points.'; end if;

  select id into existing_id from public.team_weekly_challenges where team_id=target_team_id and week_start=public.current_week_start();
  if existing_id is not null and exists(select 1 from public.game_stats gs where gs.team_challenge_id=existing_id) then
    update public.team_weekly_challenges set locked_at=coalesce(locked_at,now()) where id=existing_id;
    raise exception 'This challenge is already in progress and its setup is locked.' using errcode='55000';
  end if;

  insert into public.team_weekly_challenges(team_id,week_start,game_ids,active_days,reward_points,created_by)
  values(target_team_id,public.current_week_start(),clean_games,clean_days,coalesce(reward_points_in,0),auth.uid())
  on conflict(team_id,week_start) do update
    set game_ids=excluded.game_ids,active_days=excluded.active_days,reward_points=excluded.reward_points,updated_at=now(),created_by=auth.uid()
  returning id into result_id;
  return result_id;
end;
$$;
revoke all on function public.set_team_weekly_challenge(bigint,text[],integer[],integer) from public;
grant execute on function public.set_team_weekly_challenge(bigint,text[],integer[],integer) to authenticated;

create or replace function public.validate_team_challenge_attempt()
returns trigger language plpgsql security definer set search_path=public as $$
declare c public.team_weekly_challenges;
begin
  if new.mode is distinct from 'challenge' or new.team_challenge_id is null then return new; end if;
  select * into c from public.team_weekly_challenges where id=new.team_challenge_id;
  if not found then raise exception 'Team challenge not found.'; end if;
  if new.team_id is distinct from c.team_id then raise exception 'Team challenge does not match the selected team.'; end if;
  if new.game <> all(c.game_ids) then raise exception 'This game is not included in the team challenge.'; end if;
  if new.challenge_date < c.week_start or new.challenge_date > c.week_start+6 then raise exception 'This team challenge is not available for that date.'; end if;
  if not (extract(isodow from new.challenge_date)::integer = any(c.active_days)) then raise exception 'This team challenge is not scheduled for today.'; end if;
  if not exists(select 1 from public.team_members tm where tm.team_id=c.team_id and tm.user_id=new.user_id) then raise exception 'You are not a member of this team.'; end if;
  update public.team_weekly_challenges set locked_at=coalesce(locked_at,now()) where id=c.id;
  return new;
end;
$$;
drop trigger if exists validate_team_challenge_attempt_trigger on public.game_stats;
create trigger validate_team_challenge_attempt_trigger
before insert on public.game_stats
for each row execute function public.validate_team_challenge_attempt();

create or replace function public.award_completed_team_challenge()
returns trigger language plpgsql security definer set search_path=public as $$
declare c public.team_weekly_challenges; completed_count integer; award_created bigint; new_lifetime bigint;
begin
  if new.mode is distinct from 'challenge' or new.team_challenge_id is null then return new; end if;
  select * into c from public.team_weekly_challenges where id=new.team_challenge_id;
  if not found or c.reward_points<=0 then return new; end if;
  select count(distinct gs.game) into completed_count
  from public.game_stats gs
  where gs.user_id=new.user_id and gs.team_challenge_id=c.id and gs.game=any(c.game_ids);
  if completed_count < cardinality(c.game_ids) then return new; end if;

  insert into public.team_challenge_reward_awards(challenge_id,player_id,points)
  values(c.id,new.user_id,c.reward_points)
  on conflict(challenge_id,player_id) do nothing
  returning id into award_created;
  if award_created is null then return new; end if;

  perform public.ensure_player_progress(new.user_id);
  update public.player_progress
  set available_points=available_points+c.reward_points,
      lifetime_points=lifetime_points+c.reward_points,
      current_level=public.points_level(lifetime_points+c.reward_points),
      updated_at=now()
  where player_id=new.user_id
  returning lifetime_points into new_lifetime;

  insert into public.points_transactions(player_id,points,reason_code,metadata,created_by)
  values(new.user_id,c.reward_points,'TEAM_CHALLENGE_COMPLETED',
    jsonb_build_object('team_id',c.team_id,'team_challenge_id',c.id,'week_start',c.week_start,'reward_points',c.reward_points),new.user_id);
  return new;
end;
$$;
drop trigger if exists award_completed_team_challenge_trigger on public.game_stats;
create trigger award_completed_team_challenge_trigger
after insert on public.game_stats
for each row execute function public.award_completed_team_challenge();

notify pgrst,'reload schema';
commit;
