import { assertEquals } from "https://deno.land/std@0.224.0/assert/mod.ts";
import { createPushHandler } from "./handler.ts";

const envValues:Record<string,string>={PUSH_WORKER_SECRET:"correct",SUPABASE_URL:"url",SUPABASE_SERVICE_ROLE_KEY:"role",APNS_KEY_ID:"key",APNS_TEAM_ID:"team",APNS_PRIVATE_KEY:"private",APNS_BUNDLE_ID:"au.imbored.app"};
const request=(secret="correct",body:unknown={mode:"empty-check"})=>new Request("https://example.test",{method:"POST",headers:{authorization:`Bearer ${secret}`,"content-type":"application/json"},body:JSON.stringify(body)});
function query(count:number,calls:string[],error:unknown=null){const result={count,error};const chain:any={select(){calls.push("select");return chain;},is(){calls.push("is");return chain;},lte(){calls.push("lte");return chain;},lt(){calls.push("lt");return chain;},or(){calls.push("or");return chain;},then(resolve:(value:unknown)=>unknown){return Promise.resolve(result).then(resolve);}};return chain;}

Deno.test("missing or invalid worker secret is rejected before database access",async()=>{for(const secret of ["", "wrong"]){let clients=0;const handler=createPushHandler({env:(key)=>envValues[key],createClient:()=>{clients+=1;return{};},providerToken:async()=>"token",fetch});const response=await handler(request(secret));assertEquals(response.status,401);assertEquals(clients,0);}});
Deno.test("empty-check only performs read-only counts and never claims or contacts APNs",async()=>{const calls:string[]=[],tables:string[]=[],rpcs:string[]=[];let fetches=0;const client={from:(table:string)=>{tables.push(table);return query(table==="notification_events"?1:2,calls);},rpc:(name:string)=>{rpcs.push(name);throw new Error("write attempted");}};const handler=createPushHandler({env:(key)=>envValues[key],createClient:()=>client,providerToken:async()=>{throw new Error("APNs auth attempted");},fetch:async()=>{fetches+=1;throw new Error("APNs attempted");}});const response=await handler(request()),body=await response.json();assertEquals(response.status,200);assertEquals(body,{ok:true,mode:"empty-check",eligible:3,safeToSmokeTest:false});assertEquals(tables,["notification_events","notification_deliveries"]);assertEquals(rpcs,[]);assertEquals(fetches,0);assertEquals(calls.includes("select"),true);});
Deno.test("empty-check response is safe and reports an empty queue",async()=>{const client={from:()=>query(0,[]),rpc:()=>{throw new Error("claim attempted");}};const handler=createPushHandler({env:(key)=>envValues[key],createClient:()=>client,providerToken:async()=>"unused",fetch});const response=await handler(request()),text=await response.text();assertEquals(JSON.parse(text),{ok:true,mode:"empty-check",eligible:0,safeToSmokeTest:true});for(const sensitive of ["delivery_id","user_id","device_token","private","correct","role"])assertEquals(text.includes(sensitive),false);});
Deno.test("schema failures expose only the failed relation, code, and generic summary",async()=>{const client={from:(table:string)=>table==="notification_events"?query(0,[]):query(0,[],{code:"42703",message:"select included sensitive SQL"})};const handler=createPushHandler({env:(key)=>envValues[key],createClient:()=>client,providerToken:async()=>"unused",fetch});const response=await handler(request()),text=await response.text();assertEquals(JSON.parse(text),{ok:false,mode:"empty-check",error:"Unable to inspect push queue",diagnostic:{query:"notification_deliveries",code:"42703",message:"The live database schema or PostgREST query does not match the worker expectation."}});assertEquals(text.includes("sensitive SQL"),false);});
Deno.test("fetch-layer failures are distinguished without returning raw details",async()=>{const client={from:()=>query(0,[],{code:"",message:"TypeError: fetch failed",details:"secret transport detail"})};const handler=createPushHandler({env:(key)=>envValues[key],createClient:()=>client,providerToken:async()=>"unused",fetch});const response=await handler(request()),text=await response.text();assertEquals(JSON.parse(text),{ok:false,mode:"empty-check",error:"Unable to inspect push queue",diagnostic:{query:"notification_events",code:"FETCH_ERROR",message:"The database request failed before PostgREST returned a structured response."}});assertEquals(text.includes("secret transport detail"),false);});
Deno.test("normal mode retains the claim path",async()=>{const rpcs:string[]=[];const client={rpc:(name:string)=>{rpcs.push(name);return Promise.resolve({data:[],error:null});}};const handler=createPushHandler({env:(key)=>envValues[key],createClient:()=>client,providerToken:async()=>"unused",fetch});const response=await handler(request("correct",{}));assertEquals(await response.json(),{claimed:0,sent:0,retry:0,failed:0,invalidated:0,completion_errors:0});assertEquals(rpcs,["claim_push_deliveries"]);});

function sandboxDb(registrations:unknown[],filters:string[]){const result={data:registrations,error:null};const chain:any={select(){return chain;},eq(column:string,value:unknown){filters.push(`${column}:${value}`);return chain;},order(){return chain;},update(){throw new Error("unexpected write");},then(resolve:(value:unknown)=>unknown){return Promise.resolve(result).then(resolve);}};return{from:(table:string)=>{assertEquals(table,"push_device_registrations");return chain;},rpc:()=>{throw new Error("normal queue claimed");}};}
const sandboxRequest=(registrationId?:number)=>new Request("https://example.test",{method:"POST",headers:{authorization:"Bearer user-jwt","content-type":"application/json"},body:JSON.stringify({mode:"sandbox-self-test",...(registrationId?{registrationId}:{})})});
Deno.test("sandbox self-test rejects unauthenticated callers before database or APNs",async()=>{let clients=0,fetches=0;const handler=createPushHandler({env:(key)=>envValues[key],createClient:()=>{clients++;return{};},createUserClient:()=>({auth:{getUser:async()=>({data:{user:null},error:{}})}}),providerToken:async()=>"token",fetch:async()=>{fetches++;return new Response();}});const response=await handler(new Request("https://example.test",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode:"sandbox-self-test"})}));assertEquals(response.status,401);assertEquals(clients,0);assertEquals(fetches,0);});
Deno.test("sandbox self-test safely handles zero or multiple owned devices without sending",async()=>{for(const registrations of [[],[{id:1,last_seen_at:"now",device_token:"token-one"},{id:2,last_seen_at:"now",device_token:"token-two"}]]){let fetches=0;const filters:string[]=[];const handler=createPushHandler({env:(key)=>envValues[key],createClient:()=>sandboxDb(registrations,filters),createUserClient:()=>({auth:{getUser:async()=>({data:{user:{id:"caller"}},error:null})}}),providerToken:async()=>"token",fetch:async()=>{fetches++;return new Response();}});const response=await handler(sandboxRequest()),text=await response.text();assertEquals(fetches,0);assertEquals(text.includes("token-one"),false);assertEquals(filters.includes("user_id:caller"),true);assertEquals(filters.includes("apns_environment:sandbox"),true);}});
Deno.test("sandbox self-test sends exactly once to the explicitly selected owned sandbox registration",async()=>{let fetches=0,url="";const filters:string[]=[];const registrations=[{id:1,last_seen_at:"now",device_token:"not-selected"},{id:2,last_seen_at:"now",device_token:"selected-token"}];const handler=createPushHandler({env:(key)=>envValues[key],createClient:()=>sandboxDb(registrations,filters),createUserClient:()=>({auth:{getUser:async()=>({data:{user:{id:"caller"}},error:null})}}),providerToken:async()=>"provider",fetch:async(input)=>{fetches++;url=String(input);return new Response("{}",{status:200});}});const response=await handler(sandboxRequest(2)),text=await response.text();assertEquals(fetches,1);assertEquals(url.includes("api.sandbox.push.apple.com"),true);assertEquals(url.includes(encodeURIComponent("selected-token")),true);assertEquals(url.includes("not-selected"),false);assertEquals(text.includes("selected-token"),false);assertEquals(JSON.parse(text),{ok:true,mode:"sandbox-self-test",sent:true,status:200});});
