import { assertEquals } from "https://deno.land/std@0.224.0/assert/mod.ts";
import { createPushHandler } from "./handler.ts";

const envValues:Record<string,string>={PUSH_WORKER_SECRET:"correct",SUPABASE_URL:"url",SUPABASE_SERVICE_ROLE_KEY:"role",APNS_KEY_ID:"key",APNS_TEAM_ID:"team",APNS_PRIVATE_KEY:"private",APNS_BUNDLE_ID:"au.imbored.app"};
const request=(secret="correct",body:unknown={mode:"empty-check"})=>new Request("https://example.test",{method:"POST",headers:{authorization:`Bearer ${secret}`,"content-type":"application/json"},body:JSON.stringify(body)});
function query(count:number,calls:string[],error:unknown=null){const result={count,error};const chain:any={select(){calls.push("select");return chain;},is(){calls.push("is");return chain;},lte(){calls.push("lte");return chain;},lt(){calls.push("lt");return chain;},or(){calls.push("or");return chain;},then(resolve:(value:unknown)=>unknown){return Promise.resolve(result).then(resolve);}};return chain;}

Deno.test("missing or invalid worker secret is rejected before database access",async()=>{for(const secret of ["", "wrong"]){let clients=0;const handler=createPushHandler({env:(key)=>envValues[key],createClient:()=>{clients+=1;return{};},providerToken:async()=>"token",fetch});const response=await handler(request(secret));assertEquals(response.status,401);assertEquals(clients,0);}});
Deno.test("empty-check only performs read-only counts and never claims or contacts APNs",async()=>{const calls:string[]=[],tables:string[]=[],rpcs:string[]=[];let fetches=0;const client={from:(table:string)=>{tables.push(table);return query(table==="notification_events"?1:2,calls);},rpc:(name:string)=>{rpcs.push(name);throw new Error("write attempted");}};const handler=createPushHandler({env:(key)=>envValues[key],createClient:()=>client,providerToken:async()=>{throw new Error("APNs auth attempted");},fetch:async()=>{fetches+=1;throw new Error("APNs attempted");}});const response=await handler(request()),body=await response.json();assertEquals(response.status,200);assertEquals(body,{ok:true,mode:"empty-check",eligible:3,safeToSmokeTest:false});assertEquals(tables,["notification_events","notification_deliveries"]);assertEquals(rpcs,[]);assertEquals(fetches,0);assertEquals(calls.includes("select"),true);});
Deno.test("empty-check response is safe and reports an empty queue",async()=>{const client={from:()=>query(0,[]),rpc:()=>{throw new Error("claim attempted");}};const handler=createPushHandler({env:(key)=>envValues[key],createClient:()=>client,providerToken:async()=>"unused",fetch});const response=await handler(request()),text=await response.text();assertEquals(JSON.parse(text),{ok:true,mode:"empty-check",eligible:0,safeToSmokeTest:true});for(const sensitive of ["delivery_id","user_id","device_token","private","correct","role"])assertEquals(text.includes(sensitive),false);});
Deno.test("empty-check failures expose only the failed relation and safe error code",async()=>{const client={from:(table:string)=>table==="notification_events"?query(0,[]):query(0,[],{code:"42703",message:"sensitive detail"})};const handler=createPushHandler({env:(key)=>envValues[key],createClient:()=>client,providerToken:async()=>"unused",fetch});const response=await handler(request()),text=await response.text();assertEquals(JSON.parse(text),{ok:false,mode:"empty-check",error:"Unable to inspect push queue",diagnostic:{query:"notification_deliveries",code:"42703"}});assertEquals(text.includes("sensitive detail"),false);});
Deno.test("normal mode retains the claim path",async()=>{const rpcs:string[]=[];const client={rpc:(name:string)=>{rpcs.push(name);return Promise.resolve({data:[],error:null});}};const handler=createPushHandler({env:(key)=>envValues[key],createClient:()=>client,providerToken:async()=>"unused",fetch});const response=await handler(request("correct",{}));assertEquals(await response.json(),{claimed:0,sent:0,retry:0,failed:0,invalidated:0,completion_errors:0});assertEquals(rpcs,["claim_push_deliveries"]);});
