const GENERAL_GEO_FACTS = [
  { id: "leaning-tower-pisa", name: "Leaning Tower of Pisa", continent: "Europe", difficulty: 1, prompt: "The Leaning Tower of Pisa is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza Šikmá veža v Pise?" },
  { id: "taj-mahal-general", name: "Taj Mahal", continent: "Asia", difficulty: 1, prompt: "The Taj Mahal is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza Tádž Mahal?" },
  { id: "giza-pyramids-general", name: "Pyramids of Giza", continent: "Africa", difficulty: 1, prompt: "The Pyramids of Giza are on which continent?", skPrompt: "Na ktorom kontinente sa nachádzajú pyramídy v Gíze?" },
  { id: "chichen-itza-general", name: "Chichén Itzá", continent: "North America", difficulty: 1, prompt: "Chichén Itzá is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza Chichén Itzá?" },
  { id: "colosseum-general", name: "Colosseum", continent: "Europe", difficulty: 1, prompt: "The Colosseum is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza Koloseum?" },
  { id: "patagonia", name: "Patagonia", continent: "South America", difficulty: 1, prompt: "Patagonia spans Argentina and Chile. Which continent is it on?", skPrompt: "Patagónia sa rozprestiera v Argentíne a Čile. Na ktorom kontinente sa nachádza?" },
  { id: "alps", name: "Alps", continent: "Europe", difficulty: 1, prompt: "The Alps mountain range is on which continent?", skPrompt: "Na ktorom kontinente sa nachádzajú Alpy?" },
  { id: "vatican-smallest-state", name: "Vatican City", continent: "Europe", difficulty: 1, prompt: "Vatican City, the world's smallest sovereign state by area, is on which continent?", skPrompt: "Vatikán, najmenší suverénny štát sveta podľa rozlohy, sa nachádza na ktorom kontinente?" },
  { id: "lapland-santa", name: "Lapland", continent: "Europe", difficulty: 1, prompt: "Lapland, famous for reindeer and Santa traditions, is in which continent?", skPrompt: "Laponsko, známe sobmi a tradíciou Santa Clausa, sa nachádza na ktorom kontinente?" },
  { id: "serengeti", name: "Serengeti", continent: "Africa", difficulty: 1, prompt: "The Serengeti is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza Serengeti?" },
  { id: "galapagos", name: "Galápagos Islands", continent: "South America", difficulty: 1, prompt: "The Galápagos Islands belong to which continent?", skPrompt: "Ku ktorému kontinentu patria Galapágy?" },
  { id: "borneo", name: "Borneo", continent: "Asia", difficulty: 1, prompt: "Borneo, one of the world's largest islands, is in which continent?", skPrompt: "Borneo, jeden z najväčších ostrovov sveta, patrí ku ktorému kontinentu?" },
  { id: "petra", name: "Petra", continent: "Asia", difficulty: 1, prompt: "The ancient city of Petra is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza staroveké mesto Petra?" },
  { id: "kilimanjaro", name: "Mount Kilimanjaro", continent: "Africa", difficulty: 1, prompt: "Mount Kilimanjaro is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza Kilimandžáro?" },
  { id: "amazon-rainforest", name: "Amazon rainforest", continent: "South America", difficulty: 1, prompt: "The Amazon rainforest is primarily on which continent?", skPrompt: "Na ktorom kontinente sa prevažne nachádza Amazonský dažďový prales?" },
  { id: "great-barrier-reef-general", name: "Great Barrier Reef", continent: "Oceania", difficulty: 1, prompt: "The Great Barrier Reef belongs to which continent region?", skPrompt: "Ku ktorému kontinentu patrí Veľká koralová bariéra?" },
  { id: "matterhorn", name: "Matterhorn", continent: "Europe", difficulty: 2, prompt: "The Matterhorn is a famous mountain on which continent?", skPrompt: "Matterhorn je známy vrch na ktorom kontinente?" },
  { id: "gobi", name: "Gobi Desert", continent: "Asia", difficulty: 2, prompt: "The Gobi Desert is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza púšť Gobi?" },
  { id: "dead-sea", name: "Dead Sea", continent: "Asia", difficulty: 2, prompt: "The Dead Sea is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza Mŕtve more?" },
  { id: "bactrian-camel", name: "Wild Bactrian camel", continent: "Asia", difficulty: 2, prompt: "The wild two-humped Bactrian camel is native to which continent?", skPrompt: "Divá dvojhrbá ťava pochádza z ktorého kontinentu?" },
  { id: "alpine-chamois", name: "Alpine chamois", continent: "Europe", difficulty: 2, prompt: "The Alpine chamois is native to mountains on which continent?", skPrompt: "Kamzík vrchovský žije prirodzene v horách ktorého kontinentu?" },
  { id: "tierra-del-fuego", name: "Tierra del Fuego", continent: "South America", difficulty: 2, prompt: "Tierra del Fuego lies at the southern tip of which continent?", skPrompt: "Ohňová zem leží na južnom cípe ktorého kontinentu?" },
  { id: "sagrada-familia", name: "Sagrada Família", continent: "Europe", difficulty: 2, prompt: "Barcelona's Sagrada Família is on which continent?", skPrompt: "Sagrada Família v Barcelone sa nachádza na ktorom kontinente?" },
  { id: "angkor-wat-general", name: "Angkor Wat", continent: "Asia", difficulty: 2, prompt: "Angkor Wat is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza Angkor Wat?" },
  { id: "uluru-general", name: "Uluru", continent: "Oceania", difficulty: 2, prompt: "Uluru is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza Uluru?" },
  { id: "table-mountain-general", name: "Table Mountain", continent: "Africa", difficulty: 2, prompt: "Table Mountain overlooking Cape Town is on which continent?", skPrompt: "Stolová hora nad Kapským Mestom sa nachádza na ktorom kontinente?" },
  { id: "andes-general", name: "Andes", continent: "South America", difficulty: 2, prompt: "The Andes mountain range runs along which continent?", skPrompt: "Pohorie Andy sa tiahne pozdĺž ktorého kontinentu?" },
  { id: "himalayas-general", name: "Himalayas", continent: "Asia", difficulty: 2, prompt: "The Himalayas are on which continent?", skPrompt: "Na ktorom kontinente sa nachádzajú Himaláje?" },
  { id: "sahara-general", name: "Sahara Desert", continent: "Africa", difficulty: 2, prompt: "The Sahara Desert is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza Sahara?" },
  { id: "rockies-general", name: "Rocky Mountains", continent: "North America", difficulty: 2, prompt: "The Rocky Mountains are mainly on which continent?", skPrompt: "Skalnaté vrchy sa prevažne nachádzajú na ktorom kontinente?" },
  { id: "yellowstone", name: "Yellowstone", continent: "North America", difficulty: 2, prompt: "Yellowstone National Park is on which continent?", skPrompt: "Yellowstonský národný park sa nachádza na ktorom kontinente?" },
  { id: "great-victoria-desert", name: "Great Victoria Desert", continent: "Oceania", difficulty: 2, prompt: "The Great Victoria Desert is on which continent?", skPrompt: "Veľká Viktóriina púšť sa nachádza na ktorom kontinente?" },
  { id: "atacama-general", name: "Atacama Desert", continent: "South America", difficulty: 2, prompt: "The Atacama Desert is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza púšť Atacama?" },
  { id: "fuji-general", name: "Mount Fuji", continent: "Asia", difficulty: 2, prompt: "Mount Fuji is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza hora Fudži?" },
  { id: "iceland", name: "Iceland", continent: "Europe", difficulty: 2, prompt: "Iceland belongs to which continent?", skPrompt: "Ku ktorému kontinentu patrí Island?" },
  { id: "japan", name: "Japan", continent: "Asia", difficulty: 2, prompt: "Japan is part of which continent?", skPrompt: "Ku ktorému kontinentu patrí Japonsko?" },
  { id: "victoria-falls-general", name: "Victoria Falls", continent: "Africa", difficulty: 2, prompt: "Victoria Falls is on which continent?", skPrompt: "Na ktorom kontinente sa nachádzajú Viktóriine vodopády?" },
  { id: "machu-picchu-general", name: "Machu Picchu", continent: "South America", difficulty: 2, prompt: "Machu Picchu is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza Machu Picchu?" },
  { id: "stonehenge-general", name: "Stonehenge", continent: "Europe", difficulty: 3, prompt: "Stonehenge is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza Stonehenge?" },
  { id: "okavango", name: "Okavango Delta", continent: "Africa", difficulty: 3, prompt: "The Okavango Delta is on which continent?", skPrompt: "Na ktorom kontinente sa nachádza delta Okavanga?" },
];

export { GENERAL_GEO_FACTS };
