import { useCallback, useEffect, useState } from "react";
import { Home, Settings, Gift, Lightbulb, ClipboardCheck, Plus } from "lucide-react";
import { supabase } from "./lib/supabase.js";
import { useAuth } from "./lib/AuthContext.jsx";
const BG="#F1F3F7",PANEL="#fff",INK="#1B2129",ACCENT="#2F6FED";
const box={background:PANEL,border:"1px solid rgba(16,24,40,.09)",borderRadius:14};
export default function AdminRewards({onBack}){
 const {profile}=useAuth(); const [tab,setTab]=useState("rules"),[rules,setRules]=useState(null),[rewards,setRewards]=useState([]),[wishes,setWishes]=useState([]),[reds,setReds]=useState([]),[players,setPlayers]=useState([]),[msg,setMsg]=useState("");
 const [newReward,setNewReward]=useState({name:"",description:"",image_url:"",points_cost:"",stock_quantity:""}); const [adjust,setAdjust]=useState({player:"",amount:"",reason:""});
 const refresh=useCallback(async()=>{if(!profile?.is_admin)return; const [{data:r},{data:rw},{data:w},{data:rd},{data:p}]=await Promise.all([supabase.from("reward_rules").select("*").eq("is_active",true).maybeSingle(),supabase.from("rewards").select("*").order("created_at",{ascending:false}),supabase.from("reward_wishes").select("*,profiles(name,icon)").order("created_at",{ascending:false}),supabase.from("reward_redemptions").select("*,profiles(name,icon),rewards(name)").order("requested_at",{ascending:false}),supabase.from("profiles").select("id,name,icon").order("name")]); setRules(r);setRewards(rw||[]);setWishes(w||[]);setReds(rd||[]);setPlayers(p||[]);},[profile]); useEffect(()=>{refresh()},[refresh]);
 async function saveRules(){const {error}=await supabase.from("reward_rules").update({...rules,updated_at:new Date().toISOString(),updated_by:profile.id}).eq("id",rules.id);setMsg(error?.message||"Rules saved");refresh()}
 async function addReward(e){e.preventDefault();const payload={...newReward,points_cost:Number(newReward.points_cost),stock_quantity:newReward.stock_quantity===""?null:Number(newReward.stock_quantity),created_by:profile.id};const{error}=await supabase.from("rewards").insert(payload);setMsg(error?.message||"Reward added");if(!error)setNewReward({name:"",description:"",image_url:"",points_cost:"",stock_quantity:""});refresh()}
 async function priceWish(w,status="priced"){const value=prompt("Points cost",w.points_cost||"");if(value===null)return;const{error}=await supabase.from("reward_wishes").update({points_cost:Number(value),status,reviewed_by:profile.id,reviewed_at:new Date().toISOString()}).eq("id",w.id);setMsg(error?.message||"Wish updated");refresh()}
 async function review(id,status){const{error}=await supabase.rpc("review_redemption",{target_id:id,new_status:status,admin_note_in:null});setMsg(error?.message||"Redemption updated");refresh()}
 async function doAdjust(e){e.preventDefault();const{error}=await supabase.rpc("admin_adjust_points",{target_player_id:adjust.player,amount:Number(adjust.amount),reason:adjust.reason});setMsg(error?.message||"Points adjusted");if(!error)setAdjust({player:"",amount:"",reason:""});}
 if(!profile?.is_admin)return <div className="p-10 text-center">Admin only.</div>;
 const fields=["base_points","no_hint_bonus","no_mistake_bonus","hint_penalty","mistake_penalty","fast_time_bonus","average_time_bonus","challenge_bonus","streak_daily_bonus","streak_bonus_cap","minimum_points","maximum_points","practice_daily_limit","streak_protection_cost"];
 return <div style={{background:BG,minHeight:"100vh",fontFamily:"'Inter',sans-serif"}} className="p-4 pt-10 flex justify-center"><div className="w-full max-w-xl"><div className="flex gap-3 items-center mb-4"><button onClick={onBack} className="rounded-full px-3 py-1.5 flex gap-1 items-center text-xs" style={{background:"rgba(16,24,40,.05)"}}><Home size={14}/>Home</button><h1 className="text-2xl font-bold" style={{fontFamily:"'Fredoka',sans-serif",color:INK}}>Rewards Admin</h1></div>{msg&&<div className="p-3 mb-3 rounded-xl text-xs" style={{background:"rgba(47,111,237,.08)"}}>{msg}</div>}<div className="flex gap-1 overflow-x-auto mb-3">{[["rules","Rules",Settings],["rewards","Rewards",Gift],["wishes","Wishes",Lightbulb],["redemptions","Orders",ClipboardCheck],["adjust","Adjust",Plus]].map(([id,l,I])=><button key={id} onClick={()=>setTab(id)} className="px-3 py-2 rounded-lg text-xs font-semibold flex gap-1 items-center whitespace-nowrap" style={{background:tab===id?PANEL:"rgba(16,24,40,.05)"}}><I size={13}/>{l}</button>)}</div>
 {tab==="rules"&&rules&&<div className="p-4 grid grid-cols-2 gap-3" style={box}>{fields.map(f=><label key={f} className="text-[11px] capitalize">{f.replaceAll("_"," ")}<input type="number" value={rules[f]} onChange={e=>setRules({...rules,[f]:Number(e.target.value)})} className="block w-full mt-1 rounded-lg border px-2 py-2 text-sm"/></label>)}<button onClick={saveRules} className="col-span-2 rounded-lg py-2 text-white font-semibold text-sm" style={{background:ACCENT}}>Save rules</button></div>}
 {tab==="rewards"&&<><form onSubmit={addReward} className="p-4 mb-3 grid grid-cols-2 gap-2" style={box}><input className="col-span-2 border rounded-lg px-3 py-2 text-sm" placeholder="Reward name" value={newReward.name} onChange={e=>setNewReward({...newReward,name:e.target.value})} required/><input className="col-span-2 border rounded-lg px-3 py-2 text-sm" placeholder="Description" value={newReward.description} onChange={e=>setNewReward({...newReward,description:e.target.value})}/><input className="col-span-2 border rounded-lg px-3 py-2 text-sm" placeholder="Image URL" value={newReward.image_url} onChange={e=>setNewReward({...newReward,image_url:e.target.value})}/><input type="number" className="border rounded-lg px-3 py-2 text-sm" placeholder="Points cost" value={newReward.points_cost} onChange={e=>setNewReward({...newReward,points_cost:e.target.value})} required/><input type="number" className="border rounded-lg px-3 py-2 text-sm" placeholder="Stock (blank unlimited)" value={newReward.stock_quantity} onChange={e=>setNewReward({...newReward,stock_quantity:e.target.value})}/><button className="col-span-2 rounded-lg py-2 text-white text-sm font-semibold" style={{background:ACCENT}}>Add reward</button></form>{rewards.map(r=><div key={r.id} className="p-3 mb-2 flex items-center" style={box}><div className="flex-1"><div className="font-semibold text-sm">{r.name}</div><div className="text-xs opacity-45">{r.points_cost.toLocaleString()} Points · {r.stock_quantity??"Unlimited"} stock</div></div><button onClick={async()=>{await supabase.from("rewards").update({is_active:!r.is_active}).eq("id",r.id);refresh()}} className="text-xs">{r.is_active?"Deactivate":"Activate"}</button></div>)}</>}
 {tab==="wishes"&&wishes.map(w=><div key={w.id} className="p-3 mb-2" style={box}><div className="font-semibold text-sm">{w.profiles?.icon} {w.profiles?.name} · {w.name}</div><div className="text-xs opacity-50 mb-2">{w.status}{w.points_cost?` · ${w.points_cost.toLocaleString()} Points`:""}</div><div className="flex gap-2"><button onClick={()=>priceWish(w,"approved")} className="text-xs rounded-lg px-3 py-1.5" style={{background:"rgba(22,163,74,.1)",color:"#166534"}}>Price & approve</button><button onClick={async()=>{await supabase.from("reward_wishes").update({status:"declined",reviewed_by:profile.id,reviewed_at:new Date().toISOString()}).eq("id",w.id);refresh()}} className="text-xs">Decline</button></div></div>)}
 {tab==="redemptions"&&reds.map(r=><div key={r.id} className="p-3 mb-2" style={box}><div className="font-semibold text-sm">{r.profiles?.icon} {r.profiles?.name} · {r.rewards?.name}</div><div className="text-xs opacity-50 mb-2">{r.points_cost.toLocaleString()} Points · {r.status}</div>{r.status==="requested"&&<div className="flex gap-2"><button onClick={()=>review(r.id,"approved")} className="text-xs">Approve</button><button onClick={()=>review(r.id,"declined")} className="text-xs">Decline & refund</button></div>}{r.status==="approved"&&<button onClick={()=>review(r.id,"fulfilled")} className="text-xs">Mark fulfilled</button>}</div>)}
 {tab==="adjust"&&<form onSubmit={doAdjust} className="p-4" style={box}><select required value={adjust.player} onChange={e=>setAdjust({...adjust,player:e.target.value})} className="w-full border rounded-lg px-3 py-2 text-sm mb-2"><option value="">Player</option>{players.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input required type="number" value={adjust.amount} onChange={e=>setAdjust({...adjust,amount:e.target.value})} placeholder="Amount, negative to deduct" className="w-full border rounded-lg px-3 py-2 text-sm mb-2"/><input required value={adjust.reason} onChange={e=>setAdjust({...adjust,reason:e.target.value})} placeholder="Reason" className="w-full border rounded-lg px-3 py-2 text-sm mb-2"/><button className="w-full rounded-lg py-2 text-white text-sm font-semibold" style={{background:ACCENT}}>Apply adjustment</button></form>}
 </div></div>;
}
