import { useState,useEffect,useCallback } from "react";
import { ArrowLeft,Plus,LogOut,Crown,Clock,Check,X,UserCheck,Sparkles,AlertTriangle } from "lucide-react";
import { useAuth } from "./lib/AuthContext.jsx";
import { supabase,supabaseReady } from "./lib/supabase.js";
const BG="#F1F3F7",PANEL="#fff",INK="#1B2129",ACCENT="#2F6FED";
const TEAM_EMOJIS=["🎮","🧩","🚀","🔥","⭐","🏆","🦄","🐉","🦊","🐼","🌈","⚡","💎","👑","🎯","🛸"];
function suggestEmoji(value){
 const s=value.toLowerCase();
 const rules=[[/(space|star|galaxy|moon|astro)/,"🚀"],[/(fire|hot|flame)/,"🔥"],[/(king|queen|royal|crown)/,"👑"],[/(dragon)/,"🐉"],[/(fox)/,"🦊"],[/(panda)/,"🐼"],[/(rainbow|colour|color)/,"🌈"],[/(winner|champ|trophy)/,"🏆"],[/(target|aim|bull)/,"🎯"],[/(gem|diamond)/,"💎"],[/(magic|unicorn)/,"🦄"],[/(fast|bolt|lightning)/,"⚡"],[/(game|play)/,"🎮"],[/(puzzle|quiz|brain)/,"🧩"]];
 return rules.find(([re])=>re.test(s))?.[1]||"⭐";
}
export default function Teams({onBack}){
 const {user,profile,createTeam,joinTeam,leaveTeam}=useAuth();
 const [teams,setTeams]=useState([]),[profiles,setProfiles]=useState([]),[members,setMembers]=useState([]),[requests,setRequests]=useState([]),[loading,setLoading]=useState(true),[name,setName]=useState(""),[emoji,setEmoji]=useState("⭐"),[emojiTouched,setEmojiTouched]=useState(false),[msg,setMsg]=useState("");
 const [leaveTarget,setLeaveTarget]=useState(null),[leaving,setLeaving]=useState(false);
 const refresh=useCallback(async()=>{if(!supabaseReady)return;setLoading(true);const [{data:t},{data:p},{data:m},{data:r}]=await Promise.all([
  supabase.from("teams").select("*").order("created_at"),supabase.from("profiles").select("id,name,icon,mood,is_private,hidden_from_others"),supabase.from("team_members").select("team_id,user_id"),supabase.from("team_join_requests").select("*").order("requested_at",{ascending:false})]);setTeams(t||[]);setProfiles(p||[]);setMembers(m||[]);setRequests(r||[]);setLoading(false);await supabase.rpc("mark_my_team_request_updates_seen");},[]);
 useEffect(()=>{refresh()},[refresh]);
 const byId=Object.fromEntries(profiles.map(p=>[p.id,p])); const mine=new Set(members.filter(m=>m.user_id===user?.id).map(m=>m.team_id));
 function updateName(value){setName(value);if(!emojiTouched)setEmoji(suggestEmoji(value));}
 async function create(e){e.preventDefault();if(!name.trim())return;const{error}=await createTeam(name.trim(),emoji);setMsg(error?.message||"Team created");if(!error){setName("");setEmoji("⭐");setEmojiTouched(false);}refresh();}
 async function request(id){const{error}=await joinTeam(id);setMsg(error?.message||"Join request sent to the team owner");refresh();}
 async function decide(id,approve){const{error}=await supabase.rpc("decide_team_join_request",{request_id:id,approve});setMsg(error?.message||(approve?"Request approved":"Request declined"));refresh();}
 async function confirmLeave(){if(!leaveTarget||leaving)return;setLeaving(true);const{error}=await leaveTeam(leaveTarget.id);setMsg(error?.message||`You left ${leaveTarget.name}`);if(!error)setLeaveTarget(null);setLeaving(false);refresh();}
 return <div style={{background:BG,minHeight:"100vh",fontFamily:"'Inter',sans-serif"}} className="flex justify-center p-4 pt-10"><div className="w-full max-w-md">
  <div className="flex items-center gap-3 mb-5"><button onClick={onBack} className="rounded-full flex items-center justify-center" style={{width:34,height:34,background:"rgba(16,24,40,.05)"}}><ArrowLeft size={16}/></button><h1 className="text-2xl font-bold" style={{fontFamily:"'Fredoka',sans-serif"}}>Teams</h1></div>
  {msg&&<div className="rounded-xl p-3 mb-3 text-xs" style={{background:"rgba(47,111,237,.08)"}}>{msg}</div>}
  {profile?.hidden_from_others&&<div className="rounded-xl p-3 mb-3 text-xs" style={{background:"rgba(181,67,58,.1)",color:"#B5433A"}}>Your account is hidden by an admin, so creating or joining teams is disabled.</div>}
  {!profile?.hidden_from_others&&<form onSubmit={create} className="rounded-2xl p-3 mb-5" style={{background:PANEL,border:"1px solid rgba(16,24,40,.09)"}}><div className="flex gap-2"><button type="button" className="rounded-xl text-2xl shrink-0" style={{width:46,background:"rgba(47,111,237,.08)"}} aria-label="Selected team emoji">{emoji}</button><input value={name} onChange={e=>updateName(e.target.value)} placeholder="New team name" className="flex-1 min-w-0 rounded-xl border px-3 py-2 text-sm"/><button className="rounded-xl px-3 text-white font-semibold flex items-center gap-1" style={{background:ACCENT}}><Plus size={14}/>Create</button></div><div className="mt-3"><div className="text-[11px] opacity-45 mb-2 flex items-center gap-1"><Sparkles size={12}/>Suggested from the name — tap to change</div><div className="flex flex-wrap gap-1.5">{TEAM_EMOJIS.map(item=><button type="button" key={item} onClick={()=>{setEmoji(item);setEmojiTouched(true)}} className="rounded-lg text-lg" style={{width:34,height:34,background:item===emoji?"rgba(47,111,237,.14)":"rgba(16,24,40,.045)",border:item===emoji?"1px solid rgba(47,111,237,.35)":"1px solid transparent"}}>{item}</button>)}</div></div></form>}
  {loading?<p className="text-center opacity-40">Loading…</p>:<div className="flex flex-col gap-3">{teams.map(team=>{const roster=members.filter(m=>m.team_id===team.id).map(m=>byId[m.user_id]).filter(Boolean);const isMine=mine.has(team.id),owner=team.created_by===user?.id;const myReq=requests.find(r=>r.team_id===team.id&&r.user_id===user?.id);const pending=requests.filter(r=>r.team_id===team.id&&r.status==="pending");return <div key={team.id} className="rounded-2xl p-4" style={{background:PANEL,border:"1px solid rgba(16,24,40,.09)"}}>
   <div className="flex justify-between items-center gap-3"><div className="flex gap-2 items-center font-bold text-sm min-w-0"><span className="text-xl">{team.emoji||"⭐"}</span><span className="truncate">{team.name}</span>{owner&&<Crown size={13} style={{color:"#D9AE58",flexShrink:0}}/>}</div>{isMine?<button onClick={()=>setLeaveTarget({id:team.id,name:team.name,lastMember:roster.length===1})} className="group rounded-xl px-3 py-2 text-xs font-semibold flex gap-1.5 items-center shrink-0 transition-transform active:scale-95" style={{color:"#9F2F2A",background:"linear-gradient(180deg, rgba(239,68,68,.10), rgba(239,68,68,.06))",border:"1px solid rgba(181,67,58,.22)"}}><span className="rounded-lg flex items-center justify-center" style={{width:24,height:24,background:"rgba(181,67,58,.12)"}}><LogOut size={13}/></span><span>Leave</span></button>:myReq?.status==="pending"?<span className="text-xs flex gap-1 opacity-50"><Clock size={12}/>Requested</span>:<button disabled={profile?.hidden_from_others} onClick={()=>request(team.id)} className="rounded-full px-3 py-1.5 text-xs font-semibold disabled:opacity-30" style={{color:ACCENT,background:"rgba(47,111,237,.09)"}}>Request to join</button>}</div>
   <div className="flex flex-wrap gap-1.5 mt-3">{roster.map(m=><span key={m.id} className="rounded-full px-2 py-1 text-xs" style={{background:"rgba(16,24,40,.05)"}}>{m.icon||"🙂"} {m.name}</span>)}</div>
   {myReq&&myReq.status!=="pending"&&!isMine&&<div className="mt-3 rounded-xl p-2 text-xs flex items-center gap-2" style={{background:myReq.status==="approved"?"rgba(22,163,74,.1)":"rgba(181,67,58,.1)"}}>{myReq.status==="approved"?<Check size={13}/>:<X size={13}/>}Your request was {myReq.status}.</div>}
   {owner&&pending.length>0&&<div className="mt-4 pt-3 border-t"><div className="text-xs font-semibold mb-2 flex gap-1"><UserCheck size={13}/>Join requests</div>{pending.map(r=><div key={r.id} className="flex justify-between items-center py-1"><span className="text-xs">{byId[r.user_id]?.icon||"🙂"} {byId[r.user_id]?.name||"Player"}</span><div className="flex gap-2"><button onClick={()=>decide(r.id,true)} className="text-xs" style={{color:"#15803D"}}>Approve</button><button onClick={()=>decide(r.id,false)} className="text-xs" style={{color:"#B5433A"}}>Decline</button></div></div>)}</div>}
  </div>})}</div>}
  <p className="text-[11px] text-center opacity-35 mt-6">Team membership requires approval from the person who created the team.</p>
 </div>
 {leaveTarget&&<div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-4" style={{background:"rgba(15,23,42,.48)",backdropFilter:"blur(5px)"}} role="dialog" aria-modal="true" aria-labelledby="leave-team-title" onMouseDown={e=>{if(e.target===e.currentTarget&&!leaving)setLeaveTarget(null)}}><div className="w-full max-w-sm rounded-3xl p-5" style={{background:PANEL,boxShadow:"0 24px 70px rgba(15,23,42,.28)"}}><div className="flex items-start gap-3"><div className="rounded-2xl flex items-center justify-center shrink-0" style={{width:46,height:46,background:"rgba(181,67,58,.11)",color:"#B5433A"}}>{leaveTarget.lastMember?<AlertTriangle size={22}/>:<LogOut size={21}/>}</div><div><h2 id="leave-team-title" className="text-lg font-bold" style={{fontFamily:"'Fredoka',sans-serif",color:INK}}>Leave {leaveTarget.name}?</h2><p className="text-sm mt-1" style={{color:INK,opacity:.6}}>{leaveTarget.lastMember?"You are the final member. Leaving will also permanently remove this empty team.":"You will leave this team. You can request to join again later."}</p></div></div><div className="flex gap-2 mt-5"><button disabled={leaving} onClick={()=>setLeaveTarget(null)} className="flex-1 rounded-xl py-3 text-sm font-semibold disabled:opacity-50" style={{background:"rgba(16,24,40,.06)",color:INK}}>Stay in team</button><button disabled={leaving} onClick={confirmLeave} className="flex-1 rounded-xl py-3 text-sm font-semibold text-white flex items-center justify-center gap-2 disabled:opacity-60" style={{background:"#B5433A"}}><LogOut size={15}/>{leaving?"Leaving…":"Yes, leave"}</button></div></div></div>}
 </div>
}
