import { useState,useEffect,useCallback } from "react";
import { ArrowLeft,Plus,Crown,Clock,Check,X,UserCheck,Sparkles,CalendarDays,Lock,Gift } from "lucide-react";
import { useAuth } from "./lib/AuthContext.jsx";
import { supabase,supabaseReady } from "./lib/supabase.js";
const BG="#F1F3F7",PANEL="#fff",INK="#1B2129",ACCENT="#2F6FED";
const TEAM_EMOJIS=["🎮","🧩","🚀","🔥","⭐","🏆","🦄","🐉","🦊","🐼","🌈","⚡","💎","👑","🎯","🛸"];
const DAYS=[{id:1,label:"Mon"},{id:2,label:"Tue"},{id:3,label:"Wed"},{id:4,label:"Thu"},{id:5,label:"Fri"},{id:6,label:"Sat"},{id:7,label:"Sun"}];
const DEFAULT_GAMES=["queens","tango","zip","minisudoku","geo"];
function suggestEmoji(value){
 const s=value.toLowerCase();
 const rules=[[/(space|star|galaxy|moon|astro)/,"🚀"],[/(fire|hot|flame)/,"🔥"],[/(king|queen|royal|crown)/,"👑"],[/(dragon)/,"🐉"],[/(fox)/,"🦊"],[/(panda)/,"🐼"],[/(rainbow|colour|color)/,"🌈"],[/(winner|champ|trophy)/,"🏆"],[/(target|aim|bull)/,"🎯"],[/(gem|diamond)/,"💎"],[/(magic|unicorn)/,"🦄"],[/(fast|bolt|lightning)/,"⚡"],[/(game|play)/,"🎮"],[/(puzzle|quiz|brain)/,"🧩"]];
 return rules.find(([re])=>re.test(s))?.[1]||"⭐";
}
const defaultChallenge=()=>({games:[...DEFAULT_GAMES],days:[1,2,3,4,5,6,7],reward:100,rewardType:"points",rewardLabel:"",locked:false,challengeId:null});
export default function Teams({onBack}){
 const {user,profile,createTeam,joinTeam,leaveTeam}=useAuth();
 const [teams,setTeams]=useState([]),[profiles,setProfiles]=useState([]),[members,setMembers]=useState([]),[requests,setRequests]=useState([]),[loading,setLoading]=useState(true),[name,setName]=useState(""),[emoji,setEmoji]=useState("⭐"),[emojiTouched,setEmojiTouched]=useState(false),[msg,setMsg]=useState("");
 const [leavingTeamId,setLeavingTeamId]=useState(null);
 const [challengeEdits,setChallengeEdits]=useState({});
 const gameChoices=DEFAULT_GAMES;
 const refresh=useCallback(async()=>{if(!supabaseReady)return;setLoading(true);const [{data:t},{data:p},{data:m},{data:r},{data:c}]=await Promise.all([
  supabase.from("teams").select("*").order("created_at"),supabase.from("profiles").select("id,name,icon,mood,is_private,hidden_from_others"),supabase.from("team_members").select("team_id,user_id"),supabase.from("team_join_requests").select("*").order("requested_at",{ascending:false}),supabase.rpc("get_my_active_team_challenges")]);
  setTeams(t||[]);setProfiles(p||[]);setMembers(m||[]);setRequests(r||[]);
  setChallengeEdits(prev=>{const next={...prev};(c||[]).forEach(x=>{next[x.team_id]={games:x.game_ids||DEFAULT_GAMES,days:x.active_days||[1,2,3,4,5,6,7],reward:Number(x.reward_points??100),rewardType:x.reward_type||"points",rewardLabel:x.reward_label||"",locked:!!x.is_locked,challengeId:x.challenge_id};});return next;});
  setLoading(false);await supabase.rpc("mark_my_team_request_updates_seen");},[]);
 useEffect(()=>{refresh()},[refresh]);
 const byId=Object.fromEntries(profiles.map(p=>[p.id,p])); const mine=new Set(members.filter(m=>m.user_id===user?.id).map(m=>m.team_id));
 function updateName(value){setName(value);if(!emojiTouched)setEmoji(suggestEmoji(value));}
 async function create(e){e.preventDefault();if(!name.trim())return;const{error}=await createTeam(name.trim(),emoji);setMsg(error?.message||"Team created");if(!error){setName("");setEmoji("⭐");setEmojiTouched(false);}refresh();}
 async function request(id){const{error}=await joinTeam(id);setMsg(error?.message||"Join request sent to the team owner");refresh();}
 async function decide(id,approve){const{error}=await supabase.rpc("decide_team_join_request",{request_id:id,approve});setMsg(error?.message||(approve?"Request approved":"Request declined"));refresh();}
 function challengeFor(teamId){return challengeEdits[teamId]||defaultChallenge();}
 function patchChallenge(teamId,patch){setChallengeEdits(prev=>({...prev,[teamId]:{...defaultChallenge(),...(prev[teamId]||{}),...patch}}));}
 async function saveTeamChallenge(team){
  const edit=challengeFor(team.id);
  const{error}=await supabase.rpc("set_team_weekly_challenge",{target_team_id:team.id,selected_games:edit.games,selected_days:edit.days,reward_points_in:Number(edit.reward)||0,reward_type_in:edit.rewardType||"points",reward_label_in:edit.rewardLabel||null});
  setMsg(error?.message||"Weekly team challenge saved");if(!error)refresh();
 }
 function toggleChallengeGame(teamId,game){const edit=challengeFor(teamId);if(edit.locked)return;patchChallenge(teamId,{games:edit.games.includes(game)?edit.games.filter(x=>x!==game):[...edit.games,game]});}
 function toggleDay(teamId,day){const edit=challengeFor(teamId);if(edit.locked)return;patchChallenge(teamId,{days:edit.days.includes(day)?edit.days.filter(x=>x!==day):[...edit.days,day].sort()});}
 async function leave(team){if(leavingTeamId)return;setLeavingTeamId(team.id);const{error}=await leaveTeam(team.id);setMsg(error?.message||`You left ${team.name}`);setLeavingTeamId(null);refresh();}
 return <div style={{background:BG,minHeight:"100vh",fontFamily:"'Inter',sans-serif"}} className="flex justify-center p-4 pt-10"><div className="w-full max-w-md">
  <div className="flex items-center gap-3 mb-5"><button onClick={onBack} className="rounded-full flex items-center justify-center" style={{width:34,height:34,background:"rgba(16,24,40,.05)"}}><ArrowLeft size={16}/></button><h1 className="text-2xl font-bold" style={{fontFamily:"'Fredoka',sans-serif"}}>Teams</h1></div>
  {msg&&<div className="rounded-xl p-3 mb-3 text-xs" style={{background:"rgba(47,111,237,.08)"}}>{msg}</div>}
  {profile?.hidden_from_others&&<div className="rounded-xl p-3 mb-3 text-xs" style={{background:"rgba(181,67,58,.1)",color:"#B5433A"}}>Your account is hidden by an admin, so creating or joining teams is disabled.</div>}
  {!profile?.hidden_from_others&&<form onSubmit={create} className="rounded-2xl p-3 mb-5" style={{background:PANEL,border:"1px solid rgba(16,24,40,.09)"}}><div className="flex gap-2"><button type="button" className="rounded-xl text-2xl shrink-0" style={{width:46,background:"rgba(47,111,237,.08)"}} aria-label="Selected team emoji">{emoji}</button><input value={name} onChange={e=>updateName(e.target.value)} placeholder="New team name" className="flex-1 min-w-0 rounded-xl border px-3 py-2 text-sm"/><button className="rounded-xl px-3 text-white font-semibold flex items-center gap-1" style={{background:ACCENT}}><Plus size={14}/>Create</button></div><div className="mt-3"><div className="text-[11px] opacity-45 mb-2 flex items-center gap-1"><Sparkles size={12}/>Suggested from the name — tap to change</div><div className="flex flex-wrap gap-1.5">{TEAM_EMOJIS.map(item=><button type="button" key={item} onClick={()=>{setEmoji(item);setEmojiTouched(true)}} className="rounded-lg text-lg" style={{width:34,height:34,background:item===emoji?"rgba(47,111,237,.14)":"rgba(16,24,40,.045)",border:item===emoji?"1px solid rgba(47,111,237,.35)":"1px solid transparent"}}>{item}</button>)}</div></div></form>}
  {loading?<p className="text-center opacity-40">Loading…</p>:<div className="flex flex-col gap-3">{teams.map(team=>{const roster=members.filter(m=>m.team_id===team.id).map(m=>byId[m.user_id]).filter(Boolean);const isMine=mine.has(team.id),owner=team.created_by===user?.id;const myReq=requests.find(r=>r.team_id===team.id&&r.user_id===user?.id);const pending=requests.filter(r=>r.team_id===team.id&&r.status==="pending");const edit=challengeFor(team.id);return <div key={team.id} className="rounded-2xl p-4" style={{background:PANEL,border:"1px solid rgba(16,24,40,.09)"}}>
   <div className="flex justify-between items-center gap-3"><div className="flex gap-2 items-center font-bold text-sm min-w-0"><span className="text-xl">{team.emoji||"⭐"}</span><span className="truncate">{team.name}</span>{owner&&<Crown size={13} style={{color:"#D9AE58",flexShrink:0}}/>}</div>{isMine?<button disabled={leavingTeamId===team.id} onClick={()=>leave(team)} className="rounded-full px-3 py-1.5 text-xs font-medium shrink-0 transition-opacity disabled:opacity-40" style={{color:"#9F2F2A",background:"rgba(181,67,58,.07)",border:"1px solid rgba(181,67,58,.14)"}}>{leavingTeamId===team.id?"Leaving…":"Leave team"}</button>:myReq?.status==="pending"?<span className="text-xs flex gap-1 opacity-50"><Clock size={12}/>Requested</span>:<button disabled={profile?.hidden_from_others} onClick={()=>request(team.id)} className="rounded-full px-3 py-1.5 text-xs font-semibold disabled:opacity-30" style={{color:ACCENT,background:"rgba(47,111,237,.09)"}}>Request to join</button>}</div>
   <div className="flex flex-wrap gap-1.5 mt-3">{roster.map(m=><span key={m.id} className="rounded-full px-2 py-1 text-xs" style={{background:"rgba(16,24,40,.05)"}}>{m.icon||"🙂"} {m.name}</span>)}</div>
   {myReq&&myReq.status!=="pending"&&!isMine&&<div className="mt-3 rounded-xl p-2 text-xs flex items-center gap-2" style={{background:myReq.status==="approved"?"rgba(22,163,74,.1)":"rgba(181,67,58,.1)"}}>{myReq.status==="approved"?<Check size={13}/>:<X size={13}/>}Your request was {myReq.status}.</div>}
   {owner&&pending.length>0&&<div className="mt-4 pt-3 border-t"><div className="text-xs font-semibold mb-2 flex gap-1"><UserCheck size={13}/>Join requests</div>{pending.map(r=><div key={r.id} className="flex justify-between items-center py-1"><span className="text-xs">{byId[r.user_id]?.icon||"🙂"} {byId[r.user_id]?.name||"Player"}</span><div className="flex gap-2"><button onClick={()=>decide(r.id,true)} className="text-xs" style={{color:"#15803D"}}>Approve</button><button onClick={()=>decide(r.id,false)} className="text-xs" style={{color:"#B5433A"}}>Decline</button></div></div>)}</div>}
   {owner&&<div className="mt-4 pt-3 border-t"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-semibold flex gap-1"><CalendarDays size={13}/>This team’s weekly challenge</div><div className="text-[11px] opacity-45 mt-1">Games, playing days and reward belong only to {team.name}.</div></div>{edit.locked&&<span className="rounded-full px-2 py-1 text-[10px] font-semibold flex items-center gap-1 shrink-0" style={{background:"rgba(217,174,88,.15)",color:"#8A681D"}}><Lock size={10}/>In progress</span>}</div>
    {edit.locked&&<div className="rounded-xl p-2.5 mt-3 text-[11px]" style={{background:"rgba(217,174,88,.10)",color:"#775B1D"}}>Setup is locked because a team member has started this week’s challenge. A new setup can be created next week.</div>}
    <div className="text-[11px] font-semibold mt-3 mb-2">Included games</div><div className="flex flex-wrap gap-2">{gameChoices.map(g=>{const chosen=edit.games.includes(g);return <button disabled={edit.locked} type="button" key={g} onClick={()=>toggleChallengeGame(team.id,g)} className="rounded-full px-3 py-1.5 text-xs capitalize disabled:opacity-55" style={{background:chosen?"rgba(47,111,237,.12)":"rgba(16,24,40,.05)",color:chosen?ACCENT:INK,border:chosen?"1px solid rgba(47,111,237,.3)":"1px solid transparent"}}>{g}</button>})}</div>
    <div className="text-[11px] font-semibold mt-4 mb-2">Challenge days</div><div className="grid grid-cols-7 gap-1">{DAYS.map(d=>{const chosen=edit.days.includes(d.id);return <button disabled={edit.locked} type="button" key={d.id} onClick={()=>toggleDay(team.id,d.id)} className="rounded-lg py-2 text-[10px] font-semibold disabled:opacity-55" style={{background:chosen?"rgba(18,148,106,.12)":"rgba(16,24,40,.05)",color:chosen?"#0B7C58":INK,border:chosen?"1px solid rgba(18,148,106,.28)":"1px solid transparent"}}>{d.label}</button>})}</div>
    <div className="mt-4"><span className="text-[11px] font-semibold flex items-center gap-1 mb-2"><Gift size={12}/>Completion reward</span><div className="flex gap-2 mb-2">{["points","prize"].map(t=><button key={t} type="button" disabled={edit.locked} onClick={()=>patchChallenge(team.id,{rewardType:t})} className="rounded-full px-3 py-1.5 text-xs font-semibold" style={{background:edit.rewardType===t?"rgba(47,111,237,.14)":"rgba(16,24,40,.05)",color:edit.rewardType===t?ACCENT:INK}}>{t==="points"?"Points":"Real prize"}</button>)}</div>{edit.rewardType==="points"?<div className="flex items-center rounded-xl border px-3"><input disabled={edit.locked} type="number" min="0" max="100000" value={edit.reward} onChange={e=>patchChallenge(team.id,{reward:e.target.value})} className="w-full py-2 text-sm bg-transparent outline-none"/><span className="text-xs opacity-45">points</span></div>:<input disabled={edit.locked} value={edit.rewardLabel} onChange={e=>patchChallenge(team.id,{rewardLabel:e.target.value})} placeholder="e.g. Chocolate bar, movie ticket…" className="w-full rounded-xl border px-3 py-2 text-sm"/>}<span className="text-[10px] opacity-40 mt-1 block">Awarded after every included game is completed.</span></div>
    <button disabled={edit.locked||edit.games.length===0||edit.days.length===0} type="button" onClick={()=>saveTeamChallenge(team)} className="mt-3 rounded-xl px-3 py-2 text-xs font-semibold text-white disabled:opacity-35" style={{background:ACCENT}}>Save weekly challenge</button></div>}
  </div>})}</div>}
  <p className="text-[11px] text-center opacity-35 mt-6">Team membership requires approval from the person who created the team.</p>
 </div></div>;
}
